
package pawprint.manager;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author rowzatulzannathprerona
 */
public class signUpform extends javax.swing.JFrame {

    /**
     * Creates new form signUpform
     */
    public signUpform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        conpassField = new javax.swing.JPasswordField();
        locationfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailField.setFont(new java.awt.Font("Annai MN", 1, 24)); // NOI18N
        emailField.setBorder(null);
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 290, 40));

        usernameField.setFont(new java.awt.Font("Annai MN", 1, 24)); // NOI18N
        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 290, 40));

        passField.setFont(new java.awt.Font("Annai MN", 1, 24)); // NOI18N
        passField.setAutoscrolls(false);
        passField.setBorder(null);
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 290, 40));

        conpassField.setFont(new java.awt.Font("Annai MN", 1, 24)); // NOI18N
        conpassField.setBorder(null);
        getContentPane().add(conpassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 290, 40));

        locationfield.setFont(new java.awt.Font("Annai MN", 1, 24)); // NOI18N
        locationfield.setBorder(null);
        locationfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationfieldActionPerformed(evt);
            }
        });
        getContentPane().add(locationfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 290, 40));

        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 73, 80, 50));

        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 140, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawprint/manager/bird_picture-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 390, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pawprint/manager/SignupPage (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Openingpage op=new Openingpage();
       op.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            
        
        try{
            String loc=locationfield.getText();
             Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/powPrint?useSSL=false","root","1510791365peru#&#&");
            String sql="update login set username = ?, password = ? ";
            Statement stm=con.createStatement();
            String sql1="select * from signup where location='"+loc+"'";
            ResultSet rs=stm.executeQuery(sql1);
            PreparedStatement pstm=con.prepareStatement(sql);
            
            pstm.setString(1,usernameField.getText());
            pstm.setString(2, passField.getText());

            pstm.executeUpdate();
            
           
        
            if(usernameField.getText().isEmpty()||passField.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(rootPane, "Name and password can't be empty");
            }
            else{
             JOptionPane.showMessageDialog(rootPane, "Account created successfully");
             LoginPage lp=new LoginPage();
             lp.setVisible(true);
             this.setVisible(false);
            }
           con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void locationfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUpform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUpform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUpform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUpform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new signUpform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField conpassField;
    public static javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationfield;
    public static javax.swing.JPasswordField passField;
    public static javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
